### PR TITLE
Dependency management

### PR DESCRIPTION
**Pull request by janekolszak**

### CODE REVIEW

**Comment by janekolszak** [comment]
Please create an initial release as well

**Comment by matcornic** [comment]
You're right about releases, but I'm not sure about vendoring libraries. Usually, we do vendoring on tools/apps but not on libraries (See Hermes dependencies, you will not find any vendor).

Even Glide [says it in its recommendations](http://glide.readthedocs.io/en/latest/vendor/).

Besides, Travis runs tests everyday (then gets latest version of each dependency) to make sure Hermes generates the right data. If it fails, I'm notified very quickly.

**Comment by janekolszak** [comment]
I think they are talking about storing the `/vendor` in the repository. I added `/vendor` to .gitignore.
Only glide.yml and glide.lock are stored in the repo.

It's much better to periodically run `glide update` to avoid using possibly buggy upstream releases.
If any of the libraries changes the API and you won't be able to fix it within a day or so then we're screwed :/

**Comment by matcornic** [comment]
I think you won't be screwed if you previously vendored dependencies of your app. Hermes **and its dependencies** will be vendored. You can see it in the generated `glide.lock`, there are transitive imports like `github.com/olekukonko/tablewriter` (Hermes does not directly import `tablewriter`, but `github.com/jaytaylor/html2text` does).

Moreover, what happens if my app uses govendor (or any other go package manager) instead of glide ?

**Comment by janekolszak** [comment]
Most of the venkoring tools are interchangeable. Glide is more or less compatible with the upcoming native tool.

If I run `glide update` in my app it will download the latest HEAD from hermes dependencies. Those latest deps can have different API, and hermes won't build. To fix this I'll have to dive into those libraries, check them and hardcode hermes's deps into my glide.yml on a specific version I will find.

You can set every version to `^version` to avoid updating too often.

**Comment by matcornic** [comment]
@janekolszak used [go dep](https://github.com/golang/dep) in #16

**Pull request closed without merging**
